name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 2025.x
    paths-ignore:
      - 'README.adoc'
  pull_request:
    paths-ignore:
      - 'README.adoc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Clean and build package'
        run: ./mvnw --no-transfer-progress clean package
      
      - name: 'publish JAR'
        uses: actions/upload-artifact@v4
        with:
          name: 'neo4j_user_plugins'
          path: ${{github.workspace}}/target/TSM-statistics-1.0.0.jar
