name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 2025.x
    paths-ignore:
      - 'README.adoc'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Clean and build package'
        run: ./mvnw --no-transfer-progress clean package
      
      - name: 'publish JAR'
        uses: actions/upload-artifact@v4
        with:
          name: 'neo4j_user_plugins'
          path: ${{github.workspace}}/target/TSM-statistics-1.0.0.jar
      
  notify-panoramix:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Panoramix
        env:
          GH_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          gh api \
            --method POST \
            /repos/AlyLanier/neo4j2graph/dispatches \
            -f event_type='new-jar-file-uploaded'
